server.port: 8888
spring.application.name: config-service
eureka.instance.hostname: localhost
eureka.client.serviceUrl.defaultZone=http: //eureka-server:8761/eureka/
spring.cloud.config.server.git.default-label: main
spring.cloud.config.server.git.uri: git@github.com:leonardobarrera397/config-server-digitalmoneyhouse.git
spring.cloud.config.server.git.hostKeyAlgorithm: ssh-rsa
spring.cloud.config.server.git.privateKey:
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEAr5ON4BodJGck07RK5h74w+uVBmcc43QQ2uDAl6qSPT6nfLX1IpZX
  pWSvOmPDqMU/as4QK6PuDVc7ejrK/jOjq4fgDPGPng1iLmqkBjbvakzMJFy3jJzv46aPVk
  kvIcMIuxp7sjC8WhZnjnhv2+YwXa266VNKzf50DTePhNr6F0Wj3Pw9wImlgfRCAw76BzxV
  zHtxPU6jIpmnwUIOd07QDN1H8DlGBEGvytKxSwgNbjnmCiovTYRNqOhl/5suifIKxHaMiw
  DR2hOoVw7Rbxs0uTouf3mHldP5bh1lGip2eXm8l56rMfiJqyvky+T1qZGtPT9IsXiudc+9
  e+v4esGCnZggIgFmV+EyZJsqQHguQWguGkkcOYYiuBI4vb0F15NxjZxOJWV+SFNK93FGV1
  lrNhMd5/XVAJg2v5Mljgyt761lYVJUcZYhbi/9jDFazAOQjQgS9z0HKqakayAWYAAZZ3wB
  1Bz/llaxK1sCiPsH2SDcw/S/4c3+HEWjLNbv87HTAAAFiPDKJpbwyiaWAAAAB3NzaC1yc2
  EAAAGBAK+TjeAaHSRnJNO0SuYe+MPrlQZnHON0ENrgwJeqkj0+p3y19SKWV6Vkrzpjw6jF
  P2rOECuj7g1XO3o6yv4zo6uH4Azxj54NYi5qpAY272pMzCRct4yc7+Omj1ZJLyHDCLsae7
  IwvFoWZ454b9vmMF2tuulTSs3+dA03j4Ta+hdFo9z8PcCJpYH0QgMO+gc8Vcx7cT1OoyKZ
  p8FCDndO0AzdR/A5RgRBr8rSsUsIDW455goqL02ETajoZf+bLonyCsR2jIsA0doTqFcO0W
  8bNLk6Ln95h5XT+W4dZRoqdnl5vJeeqzH4iasr5Mvk9amRrT0/SLF4rnXPvXvr+HrBgp2Y
  ICIBZlfhMmSbKkB4LkFoLhpJHDmGIrgSOL29BdeTcY2cTiVlfkhTSvdxRldZazYTHef11Q
  CYNr+TJY4Mre+tZWFSVHGWIW4v/YwxWswDkI0IEvc9ByqmpGsgFmAAGWd8AdQc/5ZWsStb
  Aoj7B9kg3MP0v+HN/hxFoyzW7/Ox0wAAAAMBAAEAAAGBAKsyNt5S2COMpu3+GCH2BR4T8U
  VC+XoWy/B/wYqg+OLa2rjROuq0qVVNrUZDzJ4dZk6gCkhjGVTMv+PYu+HNPEOewyobx6uW
  5SrZNIISwrNlmo/CD/79bzMMTysVRO2onDTEB+ShfKZiviq+6GMEOhi9s0iavI/LEiFpEX
  m7gqt6beKl2RiJnmXuYwdUbRrtC8PMgYgDyzGLnXTlEfHnWRmSEfj7/3dbDSu48MJ2YZIe
  xl0W8PSmkoqlv/7RszkyVQsphhWQdjyNwVqQWz2qusv9oAPg8FkCe3g6e3tci7cDS3rh0z
  GvUcs6AqsdBL16FqJcxmjteBL6Thed4IpQywqDusCFpE/RyYM9IpxiZ7b7npZRid5o6DCw
  cZwKkr/NMEbe5esTLX874vDg4Pf8TCNCzxywa6DTfvGv0m5tHRDou/m6z0vccK9loUbQrA
  mtuSjVlIgGS4Jtfor8iypZZVFy1bBNt7jCQHLyvWYoqfBxA/0zfJb9IqI3MqMxn/xGsQAA
  AMACu5Of5pkACQagquSU0OulewGhAhxsril/IAy1cTWo/NMsykPRSWqmCXYZ7iWfLER/Gx
  N4L4NEPO1NT60l3mn/g6JLd1lA44ZMCJ0SZRzx9Dgcvh974zCqvHCt6In29/DIhaDsSSt2
  c+JRtcBxtbeLfTab9jSDqMskU7+fi5euPpPNb5ORGVbVxYIflzvo+xsixLcfNqAoHgA/jg
  Xn8xTNLzGd8YXSAaBND3FxVaG8bfq3cgPN9/Qtc+5oK4EmgsgAAADBAOGXLP6rq/QgaYs2
  qqHU7pOAJei4fVdo2BY0d0K0ddJ2X9FhMeX9LXrqEPLH6yrBOrBrW0EbYWUmSyYTfOg1k7
  g3vvskC/vamiOmB3sZsU2Qs2dIOp/GLE56YkGXr/oZm4VEY3Uu/foSaVekHxvE7DWdawa1
  BkOp4X4wjxD5RDaxA8jpg4b3JtFaIXQgXrzlS6T9M4+ewHCJrfAV8UMqKw0fMiQqwCpPoV
  WpP0+XYALWGVS6LpM+HIIS8YeUH/117QAAAMEAxz51NYBgAdU5RDrW50ZBkclWQwWj4Rik
  W2968kMKSvz5gnmjPCfUjfxGAJ18e+LuawCd6Qu1RVdO/lgBXllvNxtG0IHA3NKU7ruqF5
  QzsuOQQq/cRctQQ4AQcZnYvnoJOxKJDQnlBKvWH6E9FjStSE1Osk2aFZs057d8QWLhdTX8
  Y/lYZKxG8jiLTfUCptj3uuHia0ClksbiFFePFE7xEuJtZW8/PmnxxqJzI1CyvMLZfcwUSh
  /UyQnWAO+yRM6/AAAAEGJhcnJlQEFsbC1pbi1vbmUBAg==
